name: Autograding Tests
on:
  - push
  - workflow_dispatch
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Setup
      id: setup
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Setup
        setup-command: ''
        command: bash ./test/setup.sh
        timeout: 10

    - name: Get balance
      id: exercise1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Get balance
        setup-command: ''
        command: bash ./test/test_balance.sh
        input: ''
        expected-output: "PASS"
        comparison-method: exact
        timeout: 10
        max-score: 1

    - name: Create transactions
      id: exercise2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Create transactions
        setup-command: ''
        command: bash ./test/test_spend.sh
        input: ''
        expected-output: "PASS"
        comparison-method: exact
        timeout: 10
        max-score: 1

    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        EXERCISE1_RESULTS: "${{ steps.exercise1.outputs.result }}"
        EXERCISE2_RESULTS: "${{ steps.exercise2.outputs.result }}"
      with:
        runners: exercise1,exercise2
